## Uso de pandas.
### Creando DataFrame

In [1]:
# A partir de un diccionario
import pandas as pd

# Desde un diccionario
data = {
    'Ciudad': ['Madrid', 'Barcelona', 'Sevilla'],
    'Población': [3.3e6, 1.6e6, 0.7e6],
    'Temperatura': [15, 18, 20]
}
df = pd.DataFrame(data)
print("DataFrame:\n", df)

DataFrame:
       Ciudad  Población  Temperatura
0     Madrid  3300000.0           15
1  Barcelona  1600000.0           18
2    Sevilla   700000.0           20

In [2]:
df

      Ciudad  Población  Temperatura
0     Madrid  3300000.0           15
1  Barcelona  1600000.0           18
2    Sevilla   700000.0           20

In [3]:
dict = {"país": ["Brasil", "Rusia", "India", "China", "Sudáfrica"],
       "capital": ["Brasilia", "Moscú", "Nueva Dehli", "Pekín", "Pretoria"],
       "area": [8.516, 17.10, 3.286, 9.597, 1.221],
       "población": [200.4, 143.5, 1252, 1357, 52.98] }
datos = pd.DataFrame(dict)
print(datos)

        país      capital    area  población
0     Brasil     Brasilia   8.516     200.40
1      Rusia        Moscú  17.100     143.50
2      India  Nueva Dehli   3.286    1252.00
3      China        Pekín   9.597    1357.00
4  Sudáfrica     Pretoria   1.221      52.98

In [4]:
datos.index= ["BR","RU","IN","CH","SA"]

In [5]:
datos['país']

BR       Brasil
RU        Rusia
IN        India
CH        China
SA    Sudáfrica
Name: país, dtype: object

In [6]:
datos.set_index('país')

               capital    area  población
país
Brasil        Brasilia   8.516     200.40
Rusia            Moscú  17.100     143.50
India      Nueva Dehli   3.286    1252.00
China            Pekín   9.597    1357.00
Sudáfrica     Pretoria   1.221      52.98

In [7]:
print(datos["país"]["RU"])

Rusia

In [8]:
datos[["país", "capital"]]

         país      capital
BR     Brasil     Brasilia
RU      Rusia        Moscú
IN      India  Nueva Dehli
CH      China        Pekín
SA  Sudáfrica     Pretoria

In [9]:
datos[["capital"]]

        capital
BR     Brasilia
RU        Moscú
IN  Nueva Dehli
CH        Pekín
SA     Pretoria

In [10]:
datos[0:3]

      país      capital    area  población
BR  Brasil     Brasilia   8.516      200.4
RU   Rusia        Moscú  17.100      143.5
IN   India  Nueva Dehli   3.286     1252.0

In [11]:
# Filtrar ciudades con temperatura > 16
filtro = df['Temperatura'] > 16
print("Ciudades con temperatura > 16:\n", df[filtro])
# Salida:
#       Ciudad  Población  Temperatura
# 1  Barcelona  1600000.0           18
# 2   Sevilla   700000.0           20

# Usando query
print("Usando query:\n", df.query('Temperatura > 16'))
# Salida: (igual que arriba)

Ciudades con temperatura > 16:
       Ciudad  Población  Temperatura
1  Barcelona  1600000.0           18
2    Sevilla   700000.0           20
Usando query:
       Ciudad  Población  Temperatura
1  Barcelona  1600000.0           18
2    Sevilla   700000.0           20

In [12]:
import requests
url_fichero = "https://raw.githubusercontent.com/fivethirtyeight/data/master/nba-elo/nbaallelo.csv"
nombre_fichero = "nba_all_elo.csv"

response = requests.get(url_fichero) # accedemos a la URL
response.raise_for_status()  # comprueba si se ha descargado bien

with open(nombre_fichero,"wb") as f:  # Guardamos la respuesta como fichero
  f.write(response.content)
print('Terminado!')

Terminado!

In [13]:
nba_data = pd.read_csv(nombre_fichero)

In [14]:
nba_data

,gameorder,game_id,lg_id,_iscopy,year_id,date_game,seasongame,is_playoffs,team_id,fran_id,...,win_equiv,opp_id,opp_fran,opp_pts,opp_elo_i,opp_elo_n,game_location,game_result,forecast,notes
0,1,194611010TRH,NBA,0,1947,11/1/1946,1,0,TRH,Huskies,...,40.294830,NYK,Knicks,68,1300.0000,1306.7233,H,L,0.640065,NaN
1,1,194611010TRH,NBA,1,1947,11/1/1946,1,0,NYK,Knicks,...,41.705170,TRH,Huskies,66,1300.0000,1293.2767,A,W,0.359935,NaN
2,2,194611020CHS,NBA,0,1947,11/2/1946,1,0,CHS,Stags,...,42.012257,NYK,Knicks,47,1306.7233,1297.0712,H,W,0.631101,NaN
3,2,194611020CHS,NBA,1,1947,11/2/1946,2,0,NYK,Knicks,...,40.692783,CHS,Stags,63,1300.0000,1309.6521,A,L,0.368899,NaN
4,3,194611020DTF,NBA,0,1947,11/2/1946,1,0,DTF,Falcons,...,38.864048,WSC,Capitols,50,1300.0000,1320.3811,H,L,0.640065,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126309,63155,201506110CLE,NBA,0,2015,6/11/2015,100,1,CLE,Cavaliers,...,60.309792,GSW,Warriors,103,1790.9591,1809.9791,H,L,0.546572,NaN
126310,63156,201506140GSW,NBA,0,2015,6/14/2015,102,1,GSW,Warriors,...,68.013329,CLE,Cavaliers,91,1704.3949,1700.7391,H,W,0.765565,NaN
126311,63156,201506140GSW,NBA,1,2015,6/14/2015,101,1,CLE,Cavaliers,...,60.010067,GSW,Warriors,104,1809.9791,1813.6349,A,L,0.234435,NaN
126312,63157,201506170CLE,NBA,0,2015,6/16/2015,102,1,CLE,Cavaliers,...,59.290245,GSW,Warriors,105,1813.6349,1822.2881,H,L,0.481450,NaN
126313,63157,201506170CLE,NBA,1,2015,6/16/2015,103,1,GSW,Warriors,...,68.519516,CLE,Cavaliers,97,1700.7391,1692.0859,A,W,0.518550,NaN

In [15]:
nba_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126314 entries, 0 to 126313
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   gameorder      126314 non-null  int64
 1   game_id        126314 non-null  object
 2   lg_id          126314 non-null  object
 3   _iscopy        126314 non-null  int64
 4   year_id        126314 non-null  int64
 5   date_game      126314 non-null  object
 6   seasongame     126314 non-null  int64
 7   is_playoffs    126314 non-null  int64
 8   team_id        126314 non-null  object
 9   fran_id        126314 non-null  object
 10  pts            126314 non-null  int64
 11  elo_i          126314 non-null  float64
 12  elo_n          126314 non-null  float64
 13  win_equiv      126314 non-null  float64
 14  opp_id         126314 non-null  object
 15  opp_fran       126314 non-null  object
 16  opp_pts        126314 non-null  int64
 17  opp_elo_i      126314 non-null  float64
 18  opp_elo_n      126314 non-null  float64
 19  game_location  126314 non-null  object
 20  game_result    126314 non-null  object
 21  forecast       126314 non-null  float64
 22  notes          5424 non-null    object
dtypes: float64(6), int64(7), object(10)
memory usage: 22.2+ MB

In [16]:
nba_data.describe()

,gameorder,_iscopy,year_id,seasongame,is_playoffs,pts,elo_i,elo_n,win_equiv,opp_pts,opp_elo_i,opp_elo_n,forecast
count,126314.000000,126314.000000,126314.000000,126314.000000,126314.000000,126314.000000,126314.000000,126314.000000,126314.000000,126314.000000,126314.000000,126314.000000,126314.000000
mean,31579.000000,0.500000,1988.200374,43.533733,0.063857,102.729982,1495.236055,1495.236055,41.707889,102.729982,1495.236055,1495.236055,0.500000
std,18231.927643,0.500002,17.582309,25.375178,0.244499,14.814845,112.139945,112.461687,10.627332,14.814845,112.139945,112.461687,0.215252
min,1.000000,0.000000,1947.000000,1.000000,0.000000,0.000000,1091.644500,1085.774400,10.152501,0.000000,1091.644500,1085.774400,0.020447
25%,15790.000000,0.000000,1975.000000,22.000000,0.000000,93.000000,1417.237975,1416.994900,34.103035,93.000000,1417.237975,1416.994900,0.327989
50%,31579.000000,0.500000,1990.000000,43.000000,0.000000,103.000000,1500.945550,1500.954400,42.113357,103.000000,1500.945550,1500.954400,0.500000
75%,47368.000000,1.000000,2003.000000,65.000000,0.000000,112.000000,1576.060000,1576.291625,49.635328,112.000000,1576.060000,1576.291625,0.672011
max,63157.000000,1.000000,2015.000000,108.000000,1.000000,186.000000,1853.104500,1853.104500,71.112038,186.000000,1853.104500,1853.104500,0.979553

In [17]:
nba_data.describe(include=object)

,game_id,lg_id,date_game,team_id,fran_id,opp_id,opp_fran,game_location,game_result,notes
count,126314,126314,126314,126314,126314,126314,126314,126314,126314,5424
unique,63157,2,12426,104,53,104,53,3,2,231
top,201506170CLE,NBA,4/16/2014,BOS,Lakers,BOS,Lakers,H,L,at New York NY
freq,2,118016,30,5997,6024,5997,6024,63138,63157,440

In [18]:
nba_data["team_id"].value_counts()

team_id
BOS    5997
NYK    5769
LAL    5078
DET    4985
PHI    4533
       ...
PIT      60
INJ      60
TRH      60
DTF      60
SDS      11
Name: count, Length: 104, dtype: int64

In [19]:
nba_data["fran_id"].value_counts()

fran_id
Lakers          6024
Celtics         5997
Knicks          5769
Warriors        5657
Pistons         5650
Sixers          5644
Hawks           5572
Kings           5475
Wizards         4582
Spurs           4309
Bulls           4307
Pacers          4227
Thunder         4178
Rockets         4154
Nuggets         4120
Nets            4106
Suns            4080
Bucks           4034
Trailblazers    3870
Cavaliers       3810
Clippers        3733
Jazz            3555
Mavericks       3013
Heat            2371
Pelicans        2254
Magic           2207
Timberwolves    2131
Grizzlies       1657
Raptors         1634
Hornets          894
Colonels         846
Squires          799
Spirits          777
Stars            756
Sounds           697
Baltimore        467
Floridians       440
Condors          430
Capitols         291
Olympians        282
Sails            274
Stags            260
Bombers          249
Steamrollers     168
Packers           72
Redskins          65
Rebels            63
Waterloo          62
Denver            62
Ironmen           60
Jets              60
Huskies           60
Falcons           60
Name: count, dtype: int64

In [20]:
nba_data.loc[nba_data["fran_id"] == "Lakers"]

,gameorder,game_id,lg_id,_iscopy,year_id,date_game,seasongame,is_playoffs,team_id,fran_id,...,win_equiv,opp_id,opp_fran,opp_pts,opp_elo_i,opp_elo_n,game_location,game_result,forecast,notes
1136,569,194811040BLB,NBA,1,1949,11/4/1948,1,0,MNL,Lakers,...,51.218754,BLB,Baltimore,72,1507.2052,1491.9507,A,W,0.386583,NaN
1152,577,194811060WSC,NBA,1,1949,11/6/1948,2,0,MNL,Lakers,...,50.621624,WSC,Capitols,67,1481.8721,1487.9188,A,L,0.443232,NaN
1159,580,194811090BOS,NBA,1,1949,11/9/1948,3,0,MNL,Lakers,...,48.341133,BOS,Celtics,77,1359.3345,1382.0542,A,L,0.608859,NaN
1170,586,194811110NYK,NBA,1,1949,11/11/1948,4,0,MNL,Lakers,...,49.499451,NYK,Knicks,68,1460.4232,1448.9517,A,W,0.432863,NaN
1183,592,194811130PRO,NBA,1,1949,11/13/1948,5,0,MNL,Lakers,...,50.330185,PRO,Steamrollers,67,1245.9456,1237.6326,A,W,0.737010,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126016,63009,201504080DEN,NBA,1,2015,4/8/2015,78,0,LAL,Lakers,...,21.921890,DEN,Nuggets,119,1415.0565,1421.3248,A,L,0.238914,NaN
126052,63027,201504100LAL,NBA,0,2015,4/10/2015,79,0,LAL,Lakers,...,22.371969,MIN,Timberwolves,98,1283.9249,1278.4835,H,W,0.670716,NaN
126086,63044,201504120LAL,NBA,0,2015,4/12/2015,80,0,LAL,Lakers,...,21.791288,DAL,Mavericks,120,1556.2162,1563.2498,H,L,0.304769,NaN
126115,63058,201504130SAC,NBA,1,2015,4/13/2015,81,0,LAL,Lakers,...,21.422607,SAC,Kings,102,1395.6000,1400.1278,A,L,0.251263,NaN
126137,63069,201504150LAL,NBA,0,2015,4/15/2015,82,0,LAL,Lakers,...,19.985550,SAC,Kings,122,1400.1278,1418.2802,H,L,0.501819,NaN

In [21]:
nba_data.loc[nba_data["fran_id"] == "Lakers","team_id"].value_counts()

team_id
LAL    5078
MNL     946
Name: count, dtype: int64

In [24]:
nba_data.loc[nba_data["team_id"]=="MNL"]
nba_data["date_played"] = pd.to_datetime(nba_data["date_game"])

In [25]:
nba_data.info()
nba_data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126314 entries, 0 to 126313
Data columns (total 24 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   gameorder      126314 non-null  int64
 1   game_id        126314 non-null  object
 2   lg_id          126314 non-null  object
 3   _iscopy        126314 non-null  int64
 4   year_id        126314 non-null  int64
 5   date_game      126314 non-null  object
 6   seasongame     126314 non-null  int64
 7   is_playoffs    126314 non-null  int64
 8   team_id        126314 non-null  object
 9   fran_id        126314 non-null  object
 10  pts            126314 non-null  int64
 11  elo_i          126314 non-null  float64
 12  elo_n          126314 non-null  float64
 13  win_equiv      126314 non-null  float64
 14  opp_id         126314 non-null  object
 15  opp_fran       126314 non-null  object
 16  opp_pts        126314 non-null  int64
 17  opp_elo_i      126314 non-null  float64
 18  opp_elo_n      126314 non-null  float64
 19  game_location  126314 non-null  object
 20  game_result    126314 non-null  object
 21  forecast       126314 non-null  float64
 22  notes          5424 non-null    object
 23  date_played    126314 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(6), int64(7), object(10)
memory usage: 23.1+ MB

,gameorder,game_id,lg_id,_iscopy,year_id,date_game,seasongame,is_playoffs,team_id,fran_id,...,opp_id,opp_fran,opp_pts,opp_elo_i,opp_elo_n,game_location,game_result,forecast,notes,date_played
0,1,194611010TRH,NBA,0,1947,11/1/1946,1,0,TRH,Huskies,...,NYK,Knicks,68,1300.0000,1306.7233,H,L,0.640065,NaN,1946-11-01
1,1,194611010TRH,NBA,1,1947,11/1/1946,1,0,NYK,Knicks,...,TRH,Huskies,66,1300.0000,1293.2767,A,W,0.359935,NaN,1946-11-01
2,2,194611020CHS,NBA,0,1947,11/2/1946,1,0,CHS,Stags,...,NYK,Knicks,47,1306.7233,1297.0712,H,W,0.631101,NaN,1946-11-02
3,2,194611020CHS,NBA,1,1947,11/2/1946,2,0,NYK,Knicks,...,CHS,Stags,63,1300.0000,1309.6521,A,L,0.368899,NaN,1946-11-02
4,3,194611020DTF,NBA,0,1947,11/2/1946,1,0,DTF,Falcons,...,WSC,Capitols,50,1300.0000,1320.3811,H,L,0.640065,NaN,1946-11-02

In [26]:
print(nba_data.loc[nba_data["team_id"]=="MNL","date_played"].min())
print(nba_data.loc[nba_data["team_id"]=="MNL","date_played"].max())

1948-11-04 00:00:00
1960-03-26 00:00:00

In [27]:
pts_bos=nba_data.loc[nba_data["team_id"]=="BOS","pts"] # creamos la variable para usarlo más fácilmente
print(f'min:{pts_bos.min()}')
print(f'med:{int(pts_bos.sum()/pts_bos.count())}')
print(f'max:{pts_bos.max()}')
print(f'sum:{pts_bos.sum()}')

min:43
med:104
max:173
sum:626484

In [28]:
nba_data.loc[nba_data["pts"]>150 ,["team_id","pts","opp_id","opp_pts","date_played"]]

       team_id  pts opp_id  opp_pts date_played
8974       BOS  173    MNL      139  1959-02-27
9141       BOS  151    CIN      118  1959-11-11
9274       NYK  152    SYR      121  1959-12-11
9454       STL  155    NYK      129  1960-01-24
9537       BOS  153    DET      121  1960-02-10
...        ...  ...    ...      ...         ...
107739     DEN  168    SEA      116  2008-03-16
108072     SEA  151    DEN      147  2008-04-06
108174     CHI  151    MIL      135  2008-04-14
110376     PHO  154    GSW      130  2009-03-15
113037     PHO  152    MIN      114  2010-03-16

[159 rows x 5 columns]

In [29]:
nba_data.loc[((nba_data["pts"]>150) | (nba_data["opp_pts"]>150)) & (nba_data["_iscopy"]== 0) ,["team_id","pts","opp_id","opp_pts","date_played"]]

       team_id  pts opp_id  opp_pts date_played
8974       BOS  173    MNL      139  1959-02-27
9141       BOS  151    CIN      118  1959-11-11
9274       NYK  152    SYR      121  1959-12-11
9454       STL  155    NYK      129  1960-01-24
9537       BOS  153    DET      121  1960-02-10
...        ...  ...    ...      ...         ...
107739     DEN  168    SEA      116  2008-03-16
108072     SEA  151    DEN      147  2008-04-06
108175     MIL  135    CHI      151  2008-04-14
110377     GSW  130    PHO      154  2009-03-15
113037     PHO  152    MIN      114  2010-03-16

[142 rows x 5 columns]

## Tansformando un DataFrame

In [31]:
df = nba_data.copy()

In [32]:
# Sobre la copia creamos nuevas columnas

df["diferencia"]=df.pts - df.opp_pts
df.diferencia.max()

np.int64(68)

In [33]:
# También podemos renombrar columnas
df.info()
df_renamed=df.rename(columns={"game_result":"result","game_location":"location"}) # DataFrame modificado
df_renamed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126314 entries, 0 to 126313
Data columns (total 25 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   gameorder      126314 non-null  int64
 1   game_id        126314 non-null  object
 2   lg_id          126314 non-null  object
 3   _iscopy        126314 non-null  int64
 4   year_id        126314 non-null  int64
 5   date_game      126314 non-null  object
 6   seasongame     126314 non-null  int64
 7   is_playoffs    126314 non-null  int64
 8   team_id        126314 non-null  object
 9   fran_id        126314 non-null  object
 10  pts            126314 non-null  int64
 11  elo_i          126314 non-null  float64
 12  elo_n          126314 non-null  float64
 13  win_equiv      126314 non-null  float64
 14  opp_id         126314 non-null  object
 15  opp_fran       126314 non-null  object
 16  opp_pts        126314 non-null  int64
 17  opp_elo_i      126314 non-null  float64
 18  opp_elo_n      126314 non-null  float64
 19  game_location  126314 non-null  object
 20  game_result    126314 non-null  object
 21  forecast       126314 non-null  float64
 22  notes          5424 non-null    object
 23  date_played    126314 non-null  datetime64[ns]
 24  diferencia     126314 non-null  int64
dtypes: datetime64[ns](1), float64(6), int64(8), object(10)
memory usage: 24.1+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126314 entries, 0 to 126313
Data columns (total 25 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   gameorder    126314 non-null  int64
 1   game_id      126314 non-null  object
 2   lg_id        126314 non-null  object
 3   _iscopy      126314 non-null  int64
 4   year_id      126314 non-null  int64
 5   date_game    126314 non-null  object
 6   seasongame   126314 non-null  int64
 7   is_playoffs  126314 non-null  int64
 8   team_id      126314 non-null  object
 9   fran_id      126314 non-null  object
 10  pts          126314 non-null  int64
 11  elo_i        126314 non-null  float64
 12  elo_n        126314 non-null  float64
 13  win_equiv    126314 non-null  float64
 14  opp_id       126314 non-null  object
 15  opp_fran     126314 non-null  object
 16  opp_pts      126314 non-null  int64
 17  opp_elo_i    126314 non-null  float64
 18  opp_elo_n    126314 non-null  float64
 19  location     126314 non-null  object
 20  result       126314 non-null  object
 21  forecast     126314 non-null  float64
 22  notes        5424 non-null    object
 23  date_played  126314 non-null  datetime64[ns]
 24  diferencia   126314 non-null  int64
dtypes: datetime64[ns](1), float64(6), int64(8), object(10)
memory usage: 24.1+ MB

In [34]:
# O borrar columnas
print(df.shape)  # estructura inicial
df_borradas = df.drop(["elo_i","elo_n","opp_elo_i","opp_elo_n"],axis=1)
print(df.shape)  # los datos originales mantienen la forma
print(df_borradas.shape)  # dataframe sin las columnas borradas

(126314, 25)
(126314, 25)
(126314, 21)

## Limpieza de datos

In [35]:
# Podemos crear un DataFrame con las filas que no tienen datos nulos
df_with_notes=df.dropna()
df_with_notes.shape

(5424, 25)

In [36]:
# Otra opción es eliminar columnas que tienen valores nulos y no relevantes
df_without_notes=df.dropna(axis=1)
df_without_notes.shape

(126314, 24)

In [37]:
# También puede haber cassos en los que sea conveniente rellenar los valores nulos con un valor predeterminado
df_default_notes=df.copy()
df_default_notes["notes"].fillna(value="sin notas", inplace=True)
df_default_notes["notes"].describe()

/tmp/ipykernel_100604/3734458405.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_default_notes["notes"].fillna(value="sin notas", inplace=True)

count        126314
unique          232
top       sin notas
freq         120890
Name: notes, dtype: object

In [38]:
# describe nos muestra que el rango de años es correcto, entre 1947 y 2015, 
#pero que la columna "pts" tiene un valor mínimo de 0 lo que parece incorrecto.

df.describe()

,gameorder,_iscopy,year_id,seasongame,is_playoffs,pts,elo_i,elo_n,win_equiv,opp_pts,opp_elo_i,opp_elo_n,forecast,date_played,diferencia
count,126314.000000,126314.000000,126314.000000,126314.000000,126314.000000,126314.000000,126314.000000,126314.000000,126314.000000,126314.000000,126314.000000,126314.000000,126314.000000,126314,126314.000000
mean,31579.000000,0.500000,1988.200374,43.533733,0.063857,102.729982,1495.236055,1495.236055,41.707889,102.729982,1495.236055,1495.236055,0.500000,1988-04-09 00:53:18.429311104,0.000000
min,1.000000,0.000000,1947.000000,1.000000,0.000000,0.000000,1091.644500,1085.774400,10.152501,0.000000,1091.644500,1085.774400,0.020447,1946-11-01 00:00:00,-68.000000
25%,15790.000000,0.000000,1975.000000,22.000000,0.000000,93.000000,1417.237975,1416.994900,34.103035,93.000000,1417.237975,1416.994900,0.327989,1974-11-08 00:00:00,-9.000000
50%,31579.000000,0.500000,1990.000000,43.000000,0.000000,103.000000,1500.945550,1500.954400,42.113357,103.000000,1500.945550,1500.954400,0.500000,1990-02-06 00:00:00,0.000000
75%,47368.000000,1.000000,2003.000000,65.000000,0.000000,112.000000,1576.060000,1576.291625,49.635328,112.000000,1576.060000,1576.291625,0.672011,2003-03-19 00:00:00,9.000000
max,63157.000000,1.000000,2015.000000,108.000000,1.000000,186.000000,1853.104500,1853.104500,71.112038,186.000000,1853.104500,1853.104500,0.979553,2015-06-16 00:00:00,68.000000
std,18231.927643,0.500002,17.582309,25.375178,0.244499,14.814845,112.139945,112.461687,10.627332,14.814845,112.139945,112.461687,0.215252,NaN,13.374599

In [39]:
# Vemos que es una única fila:

df[df["pts"]==0]

,gameorder,game_id,lg_id,_iscopy,year_id,date_game,seasongame,is_playoffs,team_id,fran_id,...,opp_fran,opp_pts,opp_elo_i,opp_elo_n,game_location,game_result,forecast,notes,date_played,diferencia
26684,13343,197210260VIR,ABA,1,1973,10/26/1972,7,0,DNR,Nuggets,...,Squires,2,1484.1907,1487.083,A,L,0.328948,at Richmond VA; forfeit to VIR,1972-10-26,-2

In [40]:
#Podemos filtrar esa fila quedándonos con las restantes

df_valid=df[df.pts!=0]
df_valid.describe()

,gameorder,_iscopy,year_id,seasongame,is_playoffs,pts,elo_i,elo_n,win_equiv,opp_pts,opp_elo_i,opp_elo_n,forecast,date_played,diferencia
count,126313.000000,126313.000000,126313.000000,126313.000000,126313.000000,126313.000000,126313.000000,126313.000000,126313.000000,126313.000000,126313.000000,126313.00000,126313.000000,126313,126313.000000
mean,31579.144372,0.499996,1988.200494,43.534023,0.063857,102.730796,1495.236332,1495.236355,41.707899,102.730780,1495.236143,1495.23612,0.500001,1988-04-09 01:57:39.035886976,0.000016
min,1.000000,0.000000,1947.000000,1.000000,0.000000,2.000000,1091.644500,1085.774400,10.152501,0.000000,1091.644500,1085.77440,0.020447,1946-11-01 00:00:00,-68.000000
25%,15790.000000,0.000000,1975.000000,22.000000,0.000000,93.000000,1417.237800,1416.992700,34.102852,93.000000,1417.237800,1416.99270,0.327986,1974-11-08 00:00:00,-9.000000
50%,31579.000000,0.000000,1990.000000,43.000000,0.000000,103.000000,1500.947600,1500.957900,42.113422,103.000000,1500.947600,1500.95790,0.500009,1990-02-06 00:00:00,1.000000
75%,47368.000000,1.000000,2003.000000,65.000000,0.000000,112.000000,1576.060400,1576.291700,49.635475,112.000000,1576.060400,1576.29170,0.672014,2003-03-19 00:00:00,9.000000
max,63157.000000,1.000000,2015.000000,108.000000,1.000000,186.000000,1853.104500,1853.104500,71.112038,186.000000,1853.104500,1853.10450,0.979553,2015-06-16 00:00:00,68.000000
std,18231.927610,0.500002,17.582327,25.375070,0.244499,14.812083,112.140346,112.462082,10.627373,14.812192,112.140385,112.46213,0.215253,NaN,13.374651

In [42]:
# Podemos añadir reglas de validación y quedarnos con los datos que las cumplan

df["game_result"].value_counts()
df[(df.pts > df.opp_pts) & (df.game_result != "W")].empty & df[(df.pts < df.opp_pts) & (df.game_result != "L")].empty
df

,gameorder,game_id,lg_id,_iscopy,year_id,date_game,seasongame,is_playoffs,team_id,fran_id,...,opp_fran,opp_pts,opp_elo_i,opp_elo_n,game_location,game_result,forecast,notes,date_played,diferencia
0,1,194611010TRH,NBA,0,1947,11/1/1946,1,0,TRH,Huskies,...,Knicks,68,1300.0000,1306.7233,H,L,0.640065,NaN,1946-11-01,-2
1,1,194611010TRH,NBA,1,1947,11/1/1946,1,0,NYK,Knicks,...,Huskies,66,1300.0000,1293.2767,A,W,0.359935,NaN,1946-11-01,2
2,2,194611020CHS,NBA,0,1947,11/2/1946,1,0,CHS,Stags,...,Knicks,47,1306.7233,1297.0712,H,W,0.631101,NaN,1946-11-02,16
3,2,194611020CHS,NBA,1,1947,11/2/1946,2,0,NYK,Knicks,...,Stags,63,1300.0000,1309.6521,A,L,0.368899,NaN,1946-11-02,-16
4,3,194611020DTF,NBA,0,1947,11/2/1946,1,0,DTF,Falcons,...,Capitols,50,1300.0000,1320.3811,H,L,0.640065,NaN,1946-11-02,-17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126309,63155,201506110CLE,NBA,0,2015,6/11/2015,100,1,CLE,Cavaliers,...,Warriors,103,1790.9591,1809.9791,H,L,0.546572,NaN,2015-06-11,-21
126310,63156,201506140GSW,NBA,0,2015,6/14/2015,102,1,GSW,Warriors,...,Cavaliers,91,1704.3949,1700.7391,H,W,0.765565,NaN,2015-06-14,13
126311,63156,201506140GSW,NBA,1,2015,6/14/2015,101,1,CLE,Cavaliers,...,Warriors,104,1809.9791,1813.6349,A,L,0.234435,NaN,2015-06-14,-13
126312,63157,201506170CLE,NBA,0,2015,6/16/2015,102,1,CLE,Cavaliers,...,Warriors,105,1813.6349,1822.2881,H,L,0.481450,NaN,2015-06-16,-8
126313,63157,201506170CLE,NBA,1,2015,6/16/2015,103,1,GSW,Warriors,...,Cavaliers,97,1700.7391,1692.0859,A,W,0.518550,NaN,2015-06-16,8

## Trabajando con varias fuentes de datos

In [43]:
datos
datos_nuevos=pd.DataFrame({"país": ["Holanda","Japón","España"],"capital":["Amsterdam","Tokyo","Madrid"],"empleados":[10,30,32]})
datos_juntos=pd.concat([datos,datos_nuevos])
datos_juntos

         país      capital    area  población  empleados
BR     Brasil     Brasilia   8.516     200.40        NaN
RU      Rusia        Moscú  17.100     143.50        NaN
IN      India  Nueva Dehli   3.286    1252.00        NaN
CH      China        Pekín   9.597    1357.00        NaN
SA  Sudáfrica     Pretoria   1.221      52.98        NaN
0     Holanda    Amsterdam     NaN        NaN       10.0
1       Japón        Tokyo     NaN        NaN       30.0
2      España       Madrid     NaN        NaN       32.0